# -*- coding: utf-8 -*-
"""
Created on Tue Jun 18 12:09:27 2019

@author: hjiang
"""

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
import collections
class Solution:
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        scount, tcount = collections.Counter(s), collections.Counter(t)
        for t in tcount:
            if tcount[t] > scount[t]:#没有的计数为0
                return t
            
    def findTheDifference1(self, s, t):# 这个很经典，记住，非常快
        code = 0
        for ch in s + t:
            code ^= ord(ch)
        return chr(code)


    def findTheDifference2(self, s, t):#排序法
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        slist, tlist = list(s), list(t)
        slist.sort()
        tlist.sort()
        for i in range(len(slist)):
            if slist[i] != tlist[i]:
                return tlist[i]
        return tlist[-1]

    



if __name__ == "__main__":
    s = "abcd"
    t = "abcde"
    print(Solution().findTheDifference1(s,t))